### PR TITLE
Adding libraries and initial support for device independent wireless configuration

### PR DESCRIPTION
**Pull request by DPini**
Added and modified some libraries from qMp project, changed the wibed-config script so it configures the wireless devices ( with multiple channel support ) automatically, detecting them.

Fixed the usb preparation script so it doesn't erase non removable devices ( e.g. CF card in Alix 
devices )

### CODE REVIEW

**Comment by rogerpueyo** [comment]
Hi! 

I believe you have permission to merge your pull request to the repository. If you have tested thoroughly, which I believe you've done, please proceed yourself. :)

**Comment by DPini** [comment]
Hey!
I think that I can't merge any pull request because I don't have write access to this repository.
"Only those with write access to this repository can merge pull requests."

Can someone give me access or add me to the battlemesh organization account?

Thanks!

**Comment by emmdim** [comment]
I cannot add you in the writters. If Roger also cannot do it i can make the pull request and we can ask Gui for the access.

**Comment by p4u** [comment]
I added you in the Contributors team of the BattleMesh organization.

Now you should have write access, please take care :)

On 06/09/16 14:13, Manos wrote:

> I cannot add you in the writters. If Roger also cannot do it i can make the pull request and we can ask Gui for the access.

## 

./p4u

**Pull request merged**
