### PR TITLE
Changed default protocol from mesh to adhoc

### PR DESCRIPTION
**Pull request by zavalyshyn**
Adhoc seemed to be more reliable

### CODE REVIEW

**Comment by p4u** [comment]
Can you report some extra information which confirms that adhoc is more
reliable than 11s for the link layer.

On 29/07/15 18:24, Igor wrote:

> Adhoc seemed to be more reliable
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/battlemesh/wibed-packages/pull/5
> 
> -- Commit Summary --
> - Changed default protocol from mesh to adhoc
> 
> -- File Changes --
> 
> ```
> M wibed-system/files/etc/wibed.default-config (2)
> ```
> 
> -- Patch Links --
> 
> https://github.com/battlemesh/wibed-packages/pull/5.patch
> https://github.com/battlemesh/wibed-packages/pull/5.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/battlemesh/wibed-packages/pull/5

## 

./p4u

**Comment by HRogge** [comment]
If you do it to do the routing of traffic in userspace, just switching of the forwarding of data might be the better option.

**Comment by emmdim** [comment]
I will reply specifically from the WiBed point of view because my knowledge
on rest of the stuff is limited.
After using the 11s for link layer stabilization time of the links
increased and the management network was
delaying to converge.
Nevertheless, this could be an effect from layer 3 behaviour and dhcp
issues that dnsmasq was
and is causing. So not totally sure.
Maybe Igor can comment on that if he recalls the situation.

2015-07-30 16:45 GMT+02:00 Henning Rogge notifications@github.com:

**Comment by zavalyshyn** [comment]
I don't claim adhoc is in any way better. We can still use mesh. However,
considering that Wibed was down for a long time while using mesh, I
consider switching to adhoc as an option. Problem could be in using of both
protocols at the same time though.

Anyway, this is not really essential right now. Since everyone is here I
would really appreciate if you could help in updating current Wibed
firmware to the latest trunk (Chaos Calmer) as it was requested by BM
people.

**Comment by ghost** [comment]
please, close this. We pull request that change in a new branch called wbmv8 to avoid discussion now.

**Pull request closed without merging**
